version: 2
jobs:
  android:
    working_directory: ~/awesome_project
    docker:
      - image: circleci/android:api-28-node8-alpha
    steps:
      - checkout
      - attach_workspace:
          at: ~/demo-react-native
      - run: bundle check || bundle install --path vendor/bundle
      - run: npm install
      - run: cd android
      - run:
          name: fastlane
          command: bundle exec fastlane build
      - store_artifacts:
          path: android/app/build/outputs/apk/release/app-release.apk


workflows:
  version: 2
  node-android-ios:
    jobs:
      - android