version: 2
jobs:
  android:
    working_directory: ~/awesome_project
    docker:
      - image: circleci/android:api-28-node8-alpha
    steps:
      - checkout
      - run: npm install
      - run: cd android && ./gradlew assembleRelease


workflows:
  version: 2
  node-android-ios:
    jobs:
      - android